/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_harry12800_j2se_utils_Clip */

#ifndef _Included_cn_harry12800_j2se_utils_Clip
#define _Included_cn_harry12800_j2se_utils_Clip
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_harry12800_j2se_utils_Clip
 * Method:    modifyPrintByName
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_harry12800_j2se_utils_Clip_modifyPrintByName
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
